var words = "I hear Brenda's got a baby. But, Brenda's barely got a brain. "
	+ "The girl can hardly spell her name. That's not our problem, that's up to Brenda's family. "
	+ "Well let me show ya how it affects the whole community. "
	+ "Now Brenda really never knew her moms and her dad was a junky. "
	+ "Went in death to his arms, it's sad. Cause I bet Brenda doesn't even know. "
	+ "Just cause your in the ghetto doesn't mean ya can't grow. "
	+ "But oh, that's a thought, my own revelation. "
	+ "Do whatever it takes to resist the temptation. Brenda got herself a boyfriend. "
	+ "Her boyfriend was her cousin, now lets watch the joy end. "
	+ "She tried to hide her pregnancy, from her family. Went out and had a church of kids. "
	+ "As long as when the check came they got first dibs. Now Brenda's belly is gettin bigger. "
	+ "But no one seems to notice any change in her figure. "
	+ "She's 12 years old and she's having a baby. "
	+ "And yet she thinks that he'll be with her forever. "
	+ "And dreams of a world with the two of them are together, whatever. "
	+ "He left her and she had the baby solo, she had it on the bathroom floor. "
	+ "And didn't know so, she didn't know, what to throw away and what to keep. "
	+ "She wrapped the baby up and threw him in the trash heep. "
	+ "I guess she thought she'd get away. Wouldn't hear the cries. She didn't realize. "
	+ "How much the the little baby had her eyes. Now the baby's in the trash heep balling. "
	+ "Momma can't help her, but it hurts to hear her calling. Brenda wants to run away. "
	+ "Momma say, you makin' me lose pay, the social workers here everyday. "
	+ "Now Brenda's gotta make her own way. Can't go to her family, they won't let her stay. "
	+ "No money no babysitter, she couldn't keep a job. "
	+ "She tried to sell crack, but end up getting robbed. "
	+ "So now what's next, there ain't nothing left to sell. "
	+ "It's paying the rent, so she really can't complain. "
	+ "Some say the blacker the berry, the sweeter the juice. "
	+ "I say the darker the flesh then the deeper the roots. "
	+ "I give a holler to my sisters on welfare. "
	+ "Tupac cares, and don't nobody else care. "
	+ "And uhh, I know they like to beat ya down a lot. "
	+ "When you come around the block brothas clown a lot. "
	+ "But please don't cry, dry your eyes, never let up. "
	+ "Forgive but don't forget, girl keep your head up. "
	+ "And when he tells you you ain't nuttin don't believe him. "
	+ "And if he can't learn to love you you should leave him. "
	+ "Cause sista you don't need him. "
	+ "And I ain't tryin to gas ya up, I just call em how I see em. "
	+ "You know it makes me unhappy (what's that). "
	+ "When brothas make babies, and leave a young mother to be a pappy. "
	+ "And since we all came from a woman. "
	+ "Got our name from a woman and our game from a woman. "
	+ "I wonder why we take from our women. "
	+ "Why we rape our women, do we hate our women?. "
	+ "I think it's time to kill for our women. "
	+ "Time to heal our women, be real to our women. "
	+ "And if we don't we'll have a race of babies. "
	+ "That will hate the ladies, that make the babies. "
	+ "And since a man can't make one. "
	+ "He has no right to tell a woman when and where to create one. "
	+ "So will the real men get up. "
	+ "I know you're fed up ladies, but keep your head up. "
	+ "Aiyyo, I remember Marvin Gaye, used to sing ta me. "
	+ "He had me feelin like black was tha thing to be. "
	+ "And suddenly tha ghetto didn't seem so tough. "
	+ "And though we had it rough, we always had enough. "
	+ "Ran with the local crew, and had a smoke or two. "
	+ "And I realize momma really paid the price. "
	+ "She nearly gave her life, to raise me right. "
	+ "And all I had ta give her was my pipe dream. "
	+ "Of how I'd rock the mic, and make it to tha bright screen. "
	+ "I'm tryin to make a dollar out of fifteen cents. "
	+ "It's hard to be legit and still pay tha rent. "
	+ "And in the end it seems I'm headin for tha pen. "
	+ "I try and find my friends, but they're blowin in the wind. "
	+ "Last night my buddy lost his whole family. "
	+ "It's gonna take the man in me to conquer this insanity. "
	+ "It seems tha rain'll never let up. "
	+ "I try to keep my head up, and still keep from gettin wet up. "
	+ "You know it's funny when it rains it pours. "
	+ "They got money for wars, but can't feed the poor. "
	+ "Say there ain't no hope for the youth and the truth is. "
	+ "it ain't no hope for tha future. "
	+ "And then they wonder why we crazy. "
	+ "I blame my mother, for turning my brother into a crack baby. "
	+ "We ain't meant to survive, cause it's a setup. "
	+ "And even though you're fed up. "
	+ "Huh, ya got to keep your head up. "
	+ "To all the ladies havin babies on they own. "
	+ "I know it's kinda rough and you're feelin all alone. "
	+ "Daddy's long gone and he left you by ya lonesome. "
	+ "Thank the Lord for my kids, even if nobody else want em. "
	+ "Cause I think we can make it, in fact, I'm sure. "
	+ "And if you fall, stand tall and comeback for more. "
	+ "Cause ain't nuttin worse than when your son. "
	+ "wants to kno why his daddy don't love him no mo'. "
	+ "You can't complain you was dealt this. "
	+ "Because there's too many things for you to deal with. "
	+ "Dying inside, but outside you're looking fearless. "
	+ "While tears, is rollin down your cheeks. "
	+ "Ya steady hopin things don't all down this week. "
	+ "Cause if it did, you couldn't take it, and don't blame me. "
	+ "I was given this world I didn't make it. "
	+ "And now my son's getten older and older and cold. "
	+ "From havin the world on his shoulders. "
	+ "While the rich kids is drivin Benz. "
	+ "I'm still tryin to hold on to my survivin friends. "
	+ "And it's crazy, it seems it'll never let up, but. "
	+ "you got to keep your head up. "
	+ "When I was young me and my mama had beef. "
	+ "Seventeen years old kicked out on the streets. "
	+ "Though back at the time, I never thought I'd see her face. "
	+ "Ain't a woman alive that could take my mama's place. "
	+ "Suspended from school; and scared to go home, I was a fool. "
	+ "with the big boys, breakin all the rules. "
	+ "I shed tears with my baby sister. "
	+ "Over the years we was poorer than the other little kids. "
	+ "And even though we had different daddy's, the same drama. "
	+ "When things went wrong we'd blame mama. "
	+ "I reminice on the stress I caused, it was hell. "
	+ "Huggin on my mama from a jail cell. "
	+ "And who'd think in elementary?. "
	+ "Heeey! I see the penitentiary, one day. "
	+ "And runnin from the police, that's right. "
	+ "Mama catch me, put a whoopin to my backside. "
	+ "And even as a crack fiend, mama. "
	+ "You always was a black queen, mama. "
	+ "I finally understand. "
	+ "for a woman it ain't easy tryin to raise a man. "
	+ "You always was committed. "
	+ "A poor single mother on welfare, tell me how ya did it. "
	+ "There's no way I can pay you back. "
	+ "But the plan is to show you that I understand. "
	+ "You are appreciated. "
	+ "Now ain't nobody tell us it was fair. "
	+ "No love from my daddy cause the coward wasn't there. "
	+ "He passed away and I didn't cry, cause my anger. "
	+ "wouldn't let me feel for a stranger. "
	+ "They say I'm wrong and I'm heartless, but all along. "
	+ "I was lookin for a father he was gone. "
	+ "I hung around with the Thugs, and even though they sold drugs. "
	+ "They showed a young brother love. "
	+ "I moved out and started really hangin. "
	+ "I needed money of my own so I started slangin. "
	+ "I ain't guilty cause, even though I sell rocks. "
	+ "It feels good puttin money in your mailbox. "
	+ "I love payin rent when the rent's due. "
	+ "I hope ya got the diamond necklace that I sent to you. "
	+ "Cause when I was low you was there for me. "
	+ "And never left me alone because you cared for me. "
	+ "And I could see you comin home after work late. "
	+ "You're in the kitchen tryin to fix us a hot plate. "
	+ "Ya just workin with the scraps you was given. "
	+ "And mama made miracles every Thanksgivin. "
	+ "But now the road got rough, you're alone. "
	+ "You're tryin to raise two bad kids on your own. "
	+ "Pour out some liquor and I reminsce, cause through the drama. "
	+ "I can always depend on my mama. "
	+ "And when it seems that I'm hopeless. "
	+ "You say the words that can get me back in focus. "
	+ "When I was sick as a little kid. "
	+ "To keep me happy there's no limit to the things you did. "
	+ "And all my childhood memories. "
	+ "Are full of all the sweet things you did for me. "
	+ "And even though I act crazy. "
	+ "I gotta thank the Lord that you made me. "
	+ "There are no words that can express how I feel. "
	+ "You never kept a secret, always stayed real. "
	+ "And I appreciate, how you raised me. "
	+ "And all the extra love that you gave me. "
	+ "I wish I could take the pain away. "
	+ "If you can make it through the night there's a brighter day. "
	+ "Everything will be alright if ya hold on. "
	+ "It's a struggle everyday, gotta roll on. "
	+ "And there's no way I can pay you back. "
	+ "But my plan is to show you that I understand. "
	+ "You are appreciated. "
	+ "Though I walk through the valley of death. "
	+ "Back in elementary, I thrived on misery. "
	+ "Left me alone I grew up amongst a dyin breed. "
	+ "Inside my mind couldn't find a place to rest. "
	+ "until I got that Thug Life tatted on my chest. "
	+ "Tell me can you feel me? I'm not livin in the past, you wanna last. "
	+ "Be tha first to blast, remember Kato. "
	+ "No longer with us he's deceased. "
	+ "Call on the sirens, seen him murdered in the streets. "
	+ "So many homies in the cemetery, shed so many tears. "
	+ "Now that I'm strugglin in this business, by any means. "
	+ "Label me greedy gettin green, but seldom seen. "
	+ "Take me away from all the pressure, and all the pain. "
	+ "Show me some happiness again, I'm goin blind. "
	+ "I spend my time in this cell, ain't livin well. "
	+ "I know my destiny is Hell, where did I fail?. "
	+ "My life is in denial, and when I die, . "
	+ "My every move is a calculated step, to bring me closer. "
	+ "to embrace an early death, now there's nothin left. "
	+ "There was no mercy on the streets, I couldn't rest. "
	+ "I'm barely standin, bout to go to pieces, screamin peace. "
	+ "And though my soul was deleted, I couldn't see it. "
	+ "I had my mind full of demons tryin to break free. "
	+ "They planted seeds and they hatched, sparkin the flame. "
	+ "Paintin a picture of my enemies killin me, in my sleep. "
	+ "Will I survive til the mo'nin, to see the sun. "
	+ "Please Lord forgive me for my sins, cause here I come. "
	+ "Seen drivebys takin lives, little kids die. "
	+ "Wonder why as I walk by. "
	+ "Broken-hearted as I glance at the chalk line, gettin high. "
	+ "This ain't the life for me, I wanna change. "
	+ "But ain't no future right for me, I'm stuck in the game. "
	+ "I'm trapped inside a maze. "
	+ "See this Tanqueray influenced me to gettin crazy. "
	+ "Disillusioned lately, I've been really wantin babies . "
	+ "Don't trust my lady, cause she's a product of this poison. "
	+ "I'm hearin noises, think she fuckin all my boys, can't take no more. "
	+ "I'm fallin to the floor; beggin for the Lord to let me in to Heaven's door -- shed so many tears. ";

self.addEventListener("message", function(e) {
	self.postMessage(generatePacsum(e.data.len, e.data.startWith));
});

function generatePacsum(len, startWith) {
	var phrases = words.split(". ");
	var phrasesLen = phrases.length;
	var paragLen;
	var index;
	var out = "";

	for (var i = 0; i < len; i++) {
		paragLen = parseInt(Math.random() * 3) + 3;
		out += "<p>";
		
		if (i == 0 && startWith)
			out += "Tupacsum Ipsum ";

		for (var x = 0; x < paragLen; x++) {
			index = parseInt(Math.random() * phrasesLen) - 1;
			out += phrases[index] + ". ";
		}
		out += "</p>";
	}
	
	return out;
}